version: "3.9"

services:
  db:
    image: postgres:15
    container_name: pet-db
    environment:
      POSTGRES_DB: petmarket
      POSTGRES_USER: petuser
      POSTGRES_PASSWORD: 5v1234567
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: pet-backend
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=Pet.settings   # <- замените Pet если у вас другое имя проекта
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: pet-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro   # если собираете локально, можно пробросить билд

  nginx:
    image: nginx:stable-alpine
    container_name: pet-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  postgres_data:
