services:
  db:
    image: postgres:15
    container_name: pet-db
    restart: always
    env_file:
      - .env
    volumes:
      - pet_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend   # ✅ папка backend
      dockerfile: Dockerfile
    container_name: pet-backend
    restart: always
    env_file:
      - .env
    volumes:
      - pet_static_volume:/app/static
      - pet_media_volume:/app/media
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend  # ✅ папка frontend
      dockerfile: Dockerfile
    container_name: pet-frontend
    restart: always

  nginx:
    image: nginx:stable-alpine
    container_name: pet-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - pet_static_volume:/app/static
      - pet_media_volume:/app/media
    depends_on:
      - backend
      - frontend

volumes:
  pet_db_data:
  pet_static_volume:
  pet_media_volume:
