services:
  db:
    image: postgres:15
    container_name: pet-db
    environment:
      POSTGRES_DB: petmarket
      POSTGRES_USER: petuser
      POSTGRES_PASSWORD: 5v1234567
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: pet-backend
    command: gunicorn pet_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DB_NAME=petmarket
      - DB_USER=petuser
      - DB_PASSWORD=5v1234567
      - DB_HOST=db
    expose:
      - "8000"

  frontend:
    build:
      context: ./frontend
    container_name: pet-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data:
