version: '3.9'

services:
  pet-db:
    image: postgres:15
    container_name: pet-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: petuser
      POSTGRES_PASSWORD: 5v1234567
      POSTGRES_DB: petmarket
    ports:
      - "5432:5432"
    volumes:
      - pet-db-data:/var/lib/postgresql/data

  pet-backend:
    build:
      context: ./backend
    container_name: pet-backend
    command: gunicorn pet_project.wsgi:application --bind 0.0.0.0:8000
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - pet-db

  pet-frontend:
    build:
      context: ./frontend
    container_name: pet-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - pet-backend

volumes:
  pet-db-data:
