# Generated by Django 5.1.4 on 2025-12-25 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by_users', to='ads.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Просмотр питомца',
                'verbose_name_plural': 'Просмотры питомцев',
                'ordering': ['-viewed_at'],
                'unique_together': {('user', 'pet')},
            },
        ),
    ]
