# Generated by Django 5.1.4 on 2025-12-28 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_pet_last_raised_at_viewhistory'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pet',
            field=models.ForeignKey(blank=True, help_text='Объявление, по которому оставлен отзыв', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.pet'),
        ),
        migrations.AddField(
            model_name='review',
            name='transaction_completed',
            field=models.BooleanField(default=True),
        ),
    ]
