# Generated by Django 5.1.4 on 2025-12-29 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_pet_last_raised_at_viewhistory'),
        ('reviews', '0002_review_pet_review_transaction_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.pet'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
