# frontend/nginx/nginx-ssl.conf
ssl_certificate /etc/ssl/certs_local/local.crt;
ssl_certificate_key /etc/ssl/certs_local/local.key;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers off;
ssl_session_cache shared:SSL:10m;
ssl_session_timeout 10m;
ssl_ciphers HIGH:!aNULL:!MD5;
