# Generated by Django 5.1.4 on 2025-12-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_pet_last_raised_at_viewhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='last_raised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
