# Generated by Django 5.1.4 on 2026-01-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_remove_pet_age_pet_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='is_hidden',
        ),
        migrations.AddField(
            model_name='pet',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='pet',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отклонения'),
        ),
    ]
