# Generated by Django 5.1.4 on 2026-01-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_remove_pet_is_approved_remove_pet_is_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='city_slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='Слаг города'),
        ),
    ]
