# Generated by Django 5.1.4 on 2026-01-06 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_pet_city_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('service', 'Услуга'), ('product', 'Товар')], max_length=20, verbose_name='Тип')),
                ('category', models.CharField(choices=[('groomer', 'Грумер'), ('vet', 'Ветеринарная клиника'), ('transport', 'Перевозка'), ('training', 'Дрессировка'), ('boarding', 'Передержка'), ('food', 'Корм'), ('toys', 'Игрушки'), ('accessories', 'Аксессуары'), ('meds', 'Ветпрепараты'), ('other', 'Другое')], max_length=20, verbose_name='Категория')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('business_name', models.CharField(blank=True, max_length=100, verbose_name='Название компании')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена (₽)')),
                ('location', models.CharField(max_length=100, verbose_name='Местоположение')),
                ('city_slug', models.SlugField(blank=True, max_length=100, verbose_name='Слаг города')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('moderation_status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Причина отклонения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Объявление (услуга/товар)',
                'verbose_name_plural': 'Объявления (услуги/товары)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listing_images/', verbose_name='Фото')),
                ('is_primary', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.listing')),
            ],
        ),
    ]
