# Generated by Django 5.1.4 on 2026-01-08 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_favoritelisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='user',
        ),
        migrations.RemoveField(
            model_name='listingimage',
            name='listing',
        ),
        migrations.DeleteModel(
            name='FavoriteListing',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
        migrations.DeleteModel(
            name='ListingImage',
        ),
    ]
