# Generated by Django 5.1.4 on 2025-12-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avito_delivery_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Покупки с Pet Доставкой'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_company_verified',
            field=models.BooleanField(default=False, verbose_name='Компания проверена'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_trusted_seller',
            field=models.BooleanField(default=False, verbose_name='Надёжный продавец'),
        ),
    ]
