# Generated by Django 5.1.4 on 2026-01-18 18:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avito_delivery_count_user_is_company_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_verified',
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Международный формат: +79991234567', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в международном формате: +380991234567', regex='^\\+?[379]\\d{9,12}$')])),
                ('verified', models.BooleanField(default=False, help_text='Подтверждён ли номер через SMS')),
                ('verification_code', models.CharField(blank=True, help_text='Код для верификации', max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone_number', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Номер телефона',
                'verbose_name_plural': 'Номера телефонов',
            },
        ),
    ]
