# frontend/nginx/snippets/nginx-ssl.conf

ssl_certificate /etc/nginx/snippets/selfsigned.crt;
ssl_certificate_key /etc/nginx/snippets/selfsigned.key;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_ciphers HIGH:!aNULL:!MD5;
